/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmReestablecerContrasena.java
 *
 * Created on 30/10/2009, 07:06:47 PM
 */

package Contrasena;

/**
 *
 * @author guillermo
 */
public class frmRestablecerContrasena_1 extends javax.swing.JFrame {

    /** Creates new form frmReestablecerContrasena */
    public frmRestablecerContrasena_1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReestablecerContrasena = new javax.swing.JPanel();
        lblUsuario = new java.awt.Label();
        txtUsuario = new javax.swing.JTextField();
        btnRestablecer = new javax.swing.JButton();
        lblCamposObligatorios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restablecer Contraseña");

        pnlReestablecerContrasena.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Restablecer Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 0, 12), java.awt.Color.blue)); // NOI18N

        lblUsuario.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblUsuario.setText("Usuario (*) :");

        txtUsuario.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N

        btnRestablecer.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        btnRestablecer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alkhorezmi/resources/aceptar30.png"))); // NOI18N
        btnRestablecer.setText("Restablecer");
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });

        lblCamposObligatorios.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        lblCamposObligatorios.setText("(*) Campos obligatorios");

        javax.swing.GroupLayout pnlReestablecerContrasenaLayout = new javax.swing.GroupLayout(pnlReestablecerContrasena);
        pnlReestablecerContrasena.setLayout(pnlReestablecerContrasenaLayout);
        pnlReestablecerContrasenaLayout.setHorizontalGroup(
            pnlReestablecerContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReestablecerContrasenaLayout.createSequentialGroup()
                .addGroup(pnlReestablecerContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlReestablecerContrasenaLayout.createSequentialGroup()
                        .addComponent(lblCamposObligatorios)
                        .addGap(7, 7, 7)
                        .addComponent(btnRestablecer))
                    .addGroup(pnlReestablecerContrasenaLayout.createSequentialGroup()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlReestablecerContrasenaLayout.setVerticalGroup(
            pnlReestablecerContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReestablecerContrasenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReestablecerContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlReestablecerContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestablecer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCamposObligatorios))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlReestablecerContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlReestablecerContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed

}//GEN-LAST:event_btnRestablecerActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JLabel lblCamposObligatorios;
    private java.awt.Label lblUsuario;
    private javax.swing.JPanel pnlReestablecerContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
