/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmVentanaCambiaContrasena.java
 *
 * Created on 30/10/2009, 06:38:27 PM
 */

package Contrasena;

/**
 *
 * @author guillermo
 */
public class frmVentanaModificarContrasena_1 extends javax.swing.JFrame {

    /** Creates new form frmVentanaCambiaContrasena */
    public frmVentanaModificarContrasena_1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlModificarContrasena = new javax.swing.JPanel();
        lblContrasenaAnterior = new java.awt.Label();
        lblNuevaContrasena = new java.awt.Label();
        lblRepetirContrasena = new java.awt.Label();
        txtContrasenaAnterior = new javax.swing.JTextField();
        txtNuevaContrasena = new javax.swing.JTextField();
        txtRepetirContrasena = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblCamposObligatorios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar Contraseña");

        pnlModificarContrasena.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 0, 12), java.awt.Color.blue)); // NOI18N

        lblContrasenaAnterior.setFont(new java.awt.Font("DejaVu Sans", 0, 12));
        lblContrasenaAnterior.setText("Contraseña Anterior (*) :");

        lblNuevaContrasena.setFont(new java.awt.Font("DejaVu Sans", 0, 12));
        lblNuevaContrasena.setText("Nueva Contraseña (*) :");

        lblRepetirContrasena.setFont(new java.awt.Font("DejaVu Sans", 0, 12));
        lblRepetirContrasena.setText("Repetir Contraseña (*) :");

        txtContrasenaAnterior.setFont(new java.awt.Font("DejaVu Sans", 0, 12));

        txtNuevaContrasena.setFont(new java.awt.Font("DejaVu Sans", 0, 12));

        txtRepetirContrasena.setFont(new java.awt.Font("DejaVu Sans", 0, 12));

        btnCancelar.setFont(new java.awt.Font("DejaVu Sans", 0, 12));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alkhorezmi/resources/cancelar30.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("DejaVu Sans", 0, 12));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alkhorezmi/resources/aceptar30.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblCamposObligatorios.setFont(new java.awt.Font("DejaVu Sans", 0, 12));
        lblCamposObligatorios.setText("(*) Campos obligatorios");

        javax.swing.GroupLayout pnlModificarContrasenaLayout = new javax.swing.GroupLayout(pnlModificarContrasena);
        pnlModificarContrasena.setLayout(pnlModificarContrasenaLayout);
        pnlModificarContrasenaLayout.setHorizontalGroup(
            pnlModificarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificarContrasenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModificarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlModificarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlModificarContrasenaLayout.createSequentialGroup()
                            .addComponent(btnCancelar)
                            .addGap(18, 18, 18)
                            .addComponent(btnAceptar))
                        .addGroup(pnlModificarContrasenaLayout.createSequentialGroup()
                            .addGroup(pnlModificarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblRepetirContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblContrasenaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(pnlModificarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtRepetirContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNuevaContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(txtContrasenaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblCamposObligatorios))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlModificarContrasenaLayout.setVerticalGroup(
            pnlModificarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModificarContrasenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlModificarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtContrasenaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrasenaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlModificarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlModificarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRepetirContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRepetirContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlModificarContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addComponent(lblCamposObligatorios)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlModificarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlModificarContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

}//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblCamposObligatorios;
    private java.awt.Label lblContrasenaAnterior;
    private java.awt.Label lblNuevaContrasena;
    private java.awt.Label lblRepetirContrasena;
    private javax.swing.JPanel pnlModificarContrasena;
    private javax.swing.JTextField txtContrasenaAnterior;
    private javax.swing.JTextField txtNuevaContrasena;
    private javax.swing.JTextField txtRepetirContrasena;
    // End of variables declaration//GEN-END:variables

}
